name: Lint docs with Vale

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vale:
    name: Vale lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: docs/
          vale_flags: "--config=.vale.ini"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
